// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel_WebApi
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"OrderId")]
            public float OrderId { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"ProductId")]
            public float ProductId { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Quantity")]
            public float Quantity { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"VendId")]
            public float VendId { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"UserCode")]
            public float UserCode { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"OrderDate")]
            public string OrderDate { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"TotalPrice")]
            public float TotalPrice { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"IsInvoiceSent")]
            public float IsInvoiceSent { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"OrderId")]
            public float OrderId { get; set; }

            [ColumnName(@"ProductId")]
            public float ProductId { get; set; }

            [ColumnName(@"Quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"VendId")]
            public float VendId { get; set; }

            [ColumnName(@"UserCode")]
            public float UserCode { get; set; }

            [ColumnName(@"OrderDate")]
            public float[] OrderDate { get; set; }

            [ColumnName(@"TotalPrice")]
            public float TotalPrice { get; set; }

            [ColumnName(@"IsInvoiceSent")]
            public float IsInvoiceSent { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
